version: '3.3'

services:
  postgredb:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: provadb
      POSTGRES_PASSWORD: post1234
    ports:
      - '5432:5432'
    expose:
      - 5432
    env_file:
      - ../.env

volumes:
  postdb:
